"""Database config

Revision ID: 2278eaa32725
Revises: 00f3ef3bbcec
Create Date: 2025-08-18 10:21:55.944496

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2278eaa32725"
down_revision: Union[str, Sequence[str], None] = "00f3ef3bbcec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
